apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBXbU108Y1bmM6135BKsmyOGNALYDGWZ+8LRKVIv0pM9aivxiJ43+QFJA+M4YjYEXiotQ9sSdMX0oUNp2o837t4pfyK6cmBh/P06OmL+i0WqmAs3vFAMRRhu6Ple3HECaG76gwPZdmY9Y4NsCSkfpzFJsiuJ1Vl2+qIQi886qX+vJ1GF5GjHNLA4CNnJoa76uyqR+ZWeUA8Mg42IpRY8ZNOTBi5mTlWhcEwm59tUwUhko8y6xgn23D7H2xnHL2xssNRbk/vE+g74zA7p9vQIEUbKTysqBQ5C2xu+p7T882fiHjtjKjalI5K2yafHQwNiTWuDEAI+JenhvBfmizoNBdY+han5B6+89MzT9lvixvFeql3POMwf3aW+UhDPC2SdC+SBSeSVkURAHk5X3qgsJ3tmRTZ6kZNunZM8qB8kSrxCK+0zEDXBEK156rOP6K1bf1xnYr9iFbeAfG3AH2H7cM+IdT+Epb71Hq9XmPtUkB3cNZRWObd0Ty3sxiizfFyVjHalwBgrdaaNdJbQZxQ2k1BqLLk9V9CHHtWsfwYOkA4XuYv0syjeYiErsG+6zk/mK1oCwQuChBs9ONPcGILWv/paW9ngLn7+DbHWGgTPKR6wcPEifm8p+BLqrGSjNNvtFvBxf3kG8YpAyneOJIk6IGQbgl/7FE/BFFc8sDb44BqW/VfOclgWoxNPRJbkS//b9zGKHbQOiAZx6sLFLW2zcaTAfm106n5iqHx7rJf8Q8PdSCTEOrs4Euq
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

